//------------------------------------------------------------------------------
// Authors:   tspike (github.com/tspike2k)
// Copyright: Copyright (c) 2025
// License:   Boost Software License 1.0 (https://www.boost.org/LICENSE_1_0.txt)
//------------------------------------------------------------------------------
#include "opengl.h"

glGetStringFunc glGetString;
glEnableFunc glEnable;
glDisableFunc glDisable;
glClearColorFunc glClearColor;
glBlendFuncFunc glBlendFunc;
glGenBuffersFunc glGenBuffers;
glBindBufferFunc glBindBuffer;
glBufferDataFunc glBufferData;
glBindVertexArrayFunc glBindVertexArray;
glUseProgramFunc glUseProgram;
glViewportFunc glViewport;
glScissorFunc glScissor;
glClearFunc glClear;
glGetUniformLocationFunc glGetUniformLocation;
glUniformMatrix4fvFunc glUniformMatrix4fv;
glUniform1fFunc glUniform1f;
glUniform2fFunc glUniform2f;
glUniform3fFunc glUniform3f;
glUniform4fFunc glUniform4f;
glDrawElementsFunc glDrawElements;
glBindTextureFunc glBindTexture;
glGenTexturesFunc glGenTextures;
glDeleteTexturesFunc glDeleteTextures;
glTexImage2DFunc glTexImage2D;
glTexParameteriFunc glTexParameteri;
glDeleteProgramFunc glDeleteProgram;
glDebugMessageCallbackFunc glDebugMessageCallback;
glCreateShaderFunc glCreateShader;
glShaderSourceFunc glShaderSource;
glCompileShaderFunc glCompileShader;
glGetShaderivFunc glGetShaderiv;
glGetShaderInfoLogFunc glGetShaderInfoLog;
glDeleteShaderFunc glDeleteShader;
glCreateProgramFunc glCreateProgram;
glBindAttribLocationFunc glBindAttribLocation;
glAttachShaderFunc glAttachShader;
glLinkProgramFunc glLinkProgram;
glGetProgramivFunc glGetProgramiv;
glGetProgramInfoLogFunc glGetProgramInfoLog;
glDetachShaderFunc glDetachShader;
glGenVertexArraysFunc glGenVertexArrays;
glEnableVertexAttribArrayFunc glEnableVertexAttribArray;
glDisableVertexAttribArrayFunc glDisableVertexAttribArray;
glVertexAttribPointerFunc glVertexAttribPointer;
glVertexAttribIPointerFunc glVertexAttribIPointer;
glUniformBlockBindingFunc glUniformBlockBinding;
glBindBufferRangeFunc glBindBufferRange;
glGetUniformBlockIndexFunc glGetUniformBlockIndex;
glDrawArraysFunc glDrawArrays;
glCullFaceFunc glCullFace;
glFrontFaceFunc glFrontFace;
glDepthMaskFunc glDepthMask;
glDepthFuncFunc glDepthFunc;
glDepthRangeFunc glDepthRange;
glClearDepthFunc glClearDepth;
glBufferSubDataFunc glBufferSubData;

Ceabed_API void load_opengl_functions(OpenGL_Load_Sym_Func load){
    glGetString = (glGetStringFunc)load("glGetString");
    glEnable = (glEnableFunc)load("glEnable");
    glDisable = (glDisableFunc)load("glDisable");
    glClearColor = (glClearColorFunc)load("glClearColor");
    glBlendFunc = (glBlendFuncFunc)load("glBlendFunc");
    glGenBuffers = (glGenBuffersFunc)load("glGenBuffers");
    glBindBuffer = (glBindBufferFunc)load("glBindBuffer");
    glBufferData = (glBufferDataFunc)load("glBufferData");
    glBindVertexArray = (glBindVertexArrayFunc)load("glBindVertexArray");
    glUseProgram = (glUseProgramFunc)load("glUseProgram");
    glViewport = (glViewportFunc)load("glViewport");
    glScissor = (glScissorFunc)load("glScissor");
    glClear = (glClearFunc)load("glClear");
    glGetUniformLocation = (glGetUniformLocationFunc)load("glGetUniformLocation");
    glUniformMatrix4fv = (glUniformMatrix4fvFunc)load("glUniformMatrix4fv");
    glUniform1f = (glUniform1fFunc)load("glUniform1f");
    glUniform2f = (glUniform2fFunc)load("glUniform2f");
    glUniform3f = (glUniform3fFunc)load("glUniform3f");
    glUniform4f = (glUniform4fFunc)load("glUniform4f");
    glDrawElements = (glDrawElementsFunc)load("glDrawElements");
    glBindTexture = (glBindTextureFunc)load("glBindTexture");
    glGenTextures = (glGenTexturesFunc)load("glGenTextures");
    glDeleteTextures = (glDeleteTexturesFunc)load("glDeleteTextures");
    glTexImage2D = (glTexImage2DFunc)load("glTexImage2D");
    glTexParameteri = (glTexParameteriFunc)load("glTexParameteri");
    glDeleteProgram = (glDeleteProgramFunc)load("glDeleteProgram");
    glDebugMessageCallback = (glDebugMessageCallbackFunc)load("glDebugMessageCallback");
    glCreateShader = (glCreateShaderFunc)load("glCreateShader");
    glShaderSource = (glShaderSourceFunc)load("glShaderSource");
    glCompileShader = (glCompileShaderFunc)load("glCompileShader");
    glGetShaderiv = (glGetShaderivFunc)load("glGetShaderiv");
    glGetShaderInfoLog = (glGetShaderInfoLogFunc)load("glGetShaderInfoLog");
    glDeleteShader = (glDeleteShaderFunc)load("glDeleteShader");
    glCreateProgram = (glCreateProgramFunc)load("glCreateProgram");
    glBindAttribLocation = (glBindAttribLocationFunc)load("glBindAttribLocation");
    glAttachShader = (glAttachShaderFunc)load("glAttachShader");
    glLinkProgram = (glLinkProgramFunc)load("glLinkProgram");
    glGetProgramiv = (glGetProgramivFunc)load("glGetProgramiv");
    glGetProgramInfoLog = (glGetProgramInfoLogFunc)load("glGetProgramInfoLog");
    glDetachShader = (glDetachShaderFunc)load("glDetachShader");
    glGenVertexArrays = (glGenVertexArraysFunc)load("glGenVertexArrays");
    glEnableVertexAttribArray = (glEnableVertexAttribArrayFunc)load("glEnableVertexAttribArray");
    glDisableVertexAttribArray = (glDisableVertexAttribArrayFunc)load("glDisableVertexAttribArray");
    glVertexAttribPointer = (glVertexAttribPointerFunc)load("glVertexAttribPointer");
    glVertexAttribIPointer = (glVertexAttribIPointerFunc)load("glVertexAttribIPointer");;
    glUniformBlockBinding = (glUniformBlockBindingFunc)load("glUniformBlockBinding");
    glBindBufferRange = (glBindBufferRangeFunc)load("glBindBufferRange");
    glGetUniformBlockIndex = (glGetUniformBlockIndexFunc)load("glGetUniformBlockIndex");
    glDrawArrays = (glDrawArraysFunc)load("glDrawArrays");
    glCullFace = (glCullFaceFunc)load("glCullFace");
    glFrontFace = (glFrontFaceFunc)load("glFrontFace");
    glDepthMask = (glDepthMaskFunc)load("glDepthMask");
    glDepthFunc = (glDepthFuncFunc)load("glDepthFunc");
    glDepthRange = (glDepthRangeFunc)load("glDepthRange");
    glClearDepth = (glClearDepthFunc)load("glClearDepth");
    glBufferSubData = (glBufferSubDataFunc)load("glBufferSubData");
}
